<?php

use Illuminate\Database\Seeder;

class ActividadTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE TRIGO', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE MAIZ', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE AVENA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE ARROZ', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE CEBADA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE OTROS CEREALES', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO FORRAJEROS EN PRADERAS NATURALES', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO FORRAJEROS EN PRADERAS MEJORADAS O SEMBRADAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE POROTOS O FRIJOL', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO, PRODUCCIÓN DE LUPINO', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE OTRAS LEGUMBRES', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE PAPAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE CAMOTES O BATATAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE OTROS TUBÉRCULOS N.C.P', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE RAPS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE MARAVILLA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE OTRAS OLEAGINOSAS N.C.P.', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PRODUCCIÓN DE SEMILLAS DE CEREALES, LEGUMBRES, OLEAGINOSAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE REMOLACHA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE TABACO', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE FIBRAS VEGETALES INDUSTRIALES', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE PLANTAS AROMÁTICAS O MEDICINALES', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS CULTIVOS N.C.P.', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO TRADICIONAL DE HORTALIZAS FRESCAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE HORTALIZAS EN INVERNADEROS Y CULTIVOS HIDROPONICOS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO ORGÁNICO DE HORTALIZAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE PLANTAS VIVAS Y PRODUCTOS DE LA FLORICULTURA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PRODUCCIÓN DE SEMILLAS DE FLORES, PRADOS, FRUTAS Y HORTALIZAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PRODUCCIÓN EN VIVEROS; EXCEPTO ESPECIES FORESTALES', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO Y RECOLECCIÓN DE HONGOS, TRUFAS Y SAVIA; PRODUCCIÓN DE JARABE DE ARCE DE AZÚCAR Y AZÚCAR', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE UVA DESTINADA A PRODUCCIÓN DE PISCO Y AGUARDIENTE', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE UVA DESTINADA A PRODUCCIÓN DE VINO', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE UVA DE MESA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE FRUTALES EN ÁRBOLES O ARBUSTOS CON CICLO DE VIDA MAYOR A UNA TEMPORADA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE FRUTALES MENORES EN PLANTAS CON CICLO DE VIDA DE UNA TEMPORADA', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE PLANTAS CUYAS HOJAS O FRUTAS SE UTILIZAN PARA PREPARAR BEBIDAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE ESPECIAS', 'SUB_RUB_COD' => 1 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE GANADO BOVINO PARA LA PRODUCCIÓN LECHERA', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE GANADO PARA PRODUCCIÓN DE CARNE, O COMO GANADO REPRODUCTOR', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE GANADO OVINO Y/O EXPLOTACIÓN LANERA', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE EQUINOS (CABALLARES, MULARES)', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE PORCINOS', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE CARNE', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE AVES DE CORRAL PARA LA PRODUCCIÓN DE HUEVOS', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE AVES FINAS O NO TRADICIONALES', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CRÍA DE ANIMALES DOMÉSTICOS; PERROS Y GATOS', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'APICULTURA', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RANICULTURA, HELICICULTURA U OTRA ACTIVIDAD CON ANIMALES MENORES O INSECTOS', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS EXPLOTACIONES DE ANIMALES NO CLASIFICADOS EN OTRA PARTE, INCLUIDO SUS SUBPRODUCTOS', 'SUB_RUB_COD' => 2 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXPLOTACIÓN MIXTA', 'SUB_RUB_COD' => 3 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIO DE CORTE Y ENFARDADO DE FORRAJE', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIO DE RECOLECCIÓN, EMPACADO, TRILLA, DESCASCARAMIENTO Y DESGRANE; Y SIMILARES', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIO DE ROTURACIÓN SIEMBRA Y SIMILARES', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'DESTRUCCIÓN DE PLAGAS; PULVERIZACIONES, FUMIGACIONES U OTRAS', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COSECHA, PODA, AMARRE Y LABORES DE ADECUACIÓN DE LA PLANTA U OTRAS', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS SERVICIOS AGRÍCOLAS N.C.P.', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE ADIESTRAMIENTO, GUARDERÍA Y CUIDADOS DE MASCOTAS; EXCEPTO ACTIVIDADES VETERINARIAS', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS GANADEROS, EXCEPTO ACTIVIDADES VETERINARIAS', 'SUB_RUB_COD' => 4 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CAZA DE MAMÍFEROS MARINOS; EXCEPTO BALLENAS', 'SUB_RUB_COD' => 5 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CAZA ORDINARIA Y MEDIANTE TRAMPAS, Y ACTIVIDADES DE SERVICIOS CONEXAS', 'SUB_RUB_COD' => 5 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXPLOTACIÓN DE BOSQUES', 'SUB_RUB_COD' => 6 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECOLECCIÓN DE PRODUCTOS FORESTALES SILVESTRES', 'SUB_RUB_COD' => 6 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXPLOTACIÓN DE VIVEROS DE ESPECIES FORESTALES', 'SUB_RUB_COD' => 6 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE FORESTACIÓN', 'SUB_RUB_COD' => 6 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE CORTA DE MADERA', 'SUB_RUB_COD' => 6 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE CONTROL DE INCENDIOS FORESTALES', 'SUB_RUB_COD' => 6 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE SERVICIOS CONEXAS A LA SILVICULTURA N.C.P.', 'SUB_RUB_COD' => 6 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO DE ESPECIES ACUÁTICAS EN CUERPO DE AGUA DULCE', 'SUB_RUB_COD' => 7 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPRODUCCIÓN Y CRIANZAS DE PECES MARINOS', 'SUB_RUB_COD' => 7 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CULTIVO, REPRODUCCIÓN Y CRECIMIENTOS DE VEGETALES ACUÁTICOS', 'SUB_RUB_COD' => 7 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPRODUCCIÓN Y CRÍA DE MOLUSCOS Y CRUSTACEOS.', 'SUB_RUB_COD' => 7 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS RELACIONADOS CON LA ACUICULTURA, NO INCLUYE SERVICIOS PROFESIONALES Y DE EXTRACCIÓN', 'SUB_RUB_COD' => 7 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PESCA INDUSTRIAL', 'SUB_RUB_COD' => 8 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDAD PESQUERA DE BARCOS FACTORÍAS', 'SUB_RUB_COD' => 8 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PESCA ARTESANAL. EXTRACCIÓN DE RECURSOS ACUÁTICOS EN GENERAL; INCLUYE BALLENAS', 'SUB_RUB_COD' => 8 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECOLECCIÓN DE PRODUCTOS MARINOS, COMO PERLAS NATURALES, ESPONJAS, CORALES Y ALGAS.', 'SUB_RUB_COD' => 8 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS RELACIONADOS CON LA PESCA, NO INCLUYE SERVICIOS PROFESIONALES', 'SUB_RUB_COD' => 8 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN, AGLOMERACIÓN DE CARBÓN DE PIEDRA, LIGNITO Y TURBA', 'SUB_RUB_COD' => 9 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE PETRÓLEO CRUDO Y GAS NATURAL', 'SUB_RUB_COD' => 10 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE SERVICIOS RELACIONADAS CON LA EXTRACCIÓN DE PETRÓLEO Y GAS', 'SUB_RUB_COD' => 10 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE MINERALES DE URANIO Y TORIO', 'SUB_RUB_COD' => 11 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE MINERALES DE HIERRO', 'SUB_RUB_COD' => 11 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE ORO Y PLATA', 'SUB_RUB_COD' => 11 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE ZINC Y PLOMO', 'SUB_RUB_COD' => 11 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE MANGANESO', 'SUB_RUB_COD' => 11 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE OTROS MINERALES METALÍFEROS N.C.P.', 'SUB_RUB_COD' => 11 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE COBRE', 'SUB_RUB_COD' => 11 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE PIEDRA, ARENA Y ARCILLA', 'SUB_RUB_COD' => 12 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE NITRATOS Y YODO', 'SUB_RUB_COD' => 12 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE SAL', 'SUB_RUB_COD' => 12 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXTRACCIÓN DE LITIO Y CLORUROS, EXCEPTO SAL', 'SUB_RUB_COD' => 12 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXPLOTACIÓN DE OTRAS MINAS Y CANTERAS N.C.P.', 'SUB_RUB_COD' => 12 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PRODUCCIÓN, PROCESAMIENTO DE CARNES ROJAS Y PRODUCTOS CÁRNICOS', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONSERVACIÓN DE CARNES ROJAS (FRIGORÍFICOS)', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PRODUCCIÓN, PROCESAMIENTO Y CONSERVACIÓN DE CARNES DE AVE Y OTRAS CARNES DISTINTAS A LAS ROJAS', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE CECINAS, EMBUTIDOS Y CARNES EN CONSERVA.', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PRODUCCIÓN DE HARINA DE PESCADO', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS ENLATADOS DE PESCADO Y MARISCOS', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE CONGELADOS DE PESCADOS Y MARISCOS', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE PRODUCTOS AHUMADOS, SALADOS, DESHIDRATADOS Y OTROS PROCESOS SIMILARES', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE PRODUCTOS EN BASE A VEGETALES ACUÁTICOS', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN Y CONSERVACIÓN DE FRUTAS, LEGUMBRES Y HORTALIZAS', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN VEGETAL', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN ANIMAL, EXCEPTO LAS MANTEQUILLAS', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN MARINO', 'SUB_RUB_COD' => 13 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE LECHE, MANTEQUILLA, PRODUCTOS LÁCTEOS Y DERIVADOS', 'SUB_RUB_COD' => 14 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE QUESOS', 'SUB_RUB_COD' => 14 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE POSTRES A BASE DE LECHE (HELADOS, SORBETES Y OTROS SIMILARES)', 'SUB_RUB_COD' => 14 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE HARINAS DE TRIGO', 'SUB_RUB_COD' => 15 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE MOLIENDA DE ARROZ', 'SUB_RUB_COD' => 15 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE OTRAS MOLINERAS Y ALIMENTOS A BASE DE CEREALES', 'SUB_RUB_COD' => 15 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE ALMIDONES Y PRODUCTOS DERIVADOS DEL ALMIDÓN', 'SUB_RUB_COD' => 15 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE GLUCOSA Y OTROS AZÚCARES DIFERENTES DE LA REMOLACHA', 'SUB_RUB_COD' => 15 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE ALIMENTOS PREPARADOS PARA ANIMALES', 'SUB_RUB_COD' => 15 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PAN, PRODUCTOS DE PANADERÍA Y PASTELERÍA', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE GALLETAS', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE AZÚCAR DE REMOLACHA O CANA', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE CACAO Y CHOCOLATES', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE CONFITERÍA', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE MACARRONES, FIDEOS, ALCUZCUZ Y PRODUCTOS FARINACEOS SIMILARES', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE TE, CAFÉ, INFUSIONES', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE LEVADURAS NATURALES O ARTIFICIALES', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE VINAGRES, MOSTAZAS, MAYONESAS Y CONDIMENTOS EN GENERAL', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE OTROS PRODUCTOS ALIMENTICIOS NO CLASIFICADOS EN OTRA PARTE', 'SUB_RUB_COD' => 16 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE PISCOS (INDUSTRIAS PISQUERAS)', 'SUB_RUB_COD' => 17 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE BEBIDAS ALCOHÓLICAS Y DE ALCOHOL ETÍLICO A PARTIR DE SUSTANCIAS FERMENTADAS Y OTROS', 'SUB_RUB_COD' => 17 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE VINOS', 'SUB_RUB_COD' => 17 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE BEBIDAS MALTEADAS, CERVEZAS Y MALTAS', 'SUB_RUB_COD' => 17 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE BEBIDAS NO ALCOHÓLICAS', 'SUB_RUB_COD' => 17 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ENVASADO DE AGUA MINERAL NATURAL, DE MANANTIAL Y POTABLE PREPARADA', 'SUB_RUB_COD' => 17 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE HIELO', 'SUB_RUB_COD' => 17 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CIGARROS Y CIGARRILLOS', 'SUB_RUB_COD' => 18 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS DEL TABACO', 'SUB_RUB_COD' => 18 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PREPARACIÓN DE HILATURA DE FIBRAS TEXTILES; TEJEDURA PROD. TEXTILES', 'SUB_RUB_COD' => 19 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACABADO DE PRODUCTOS TEXTIL', 'SUB_RUB_COD' => 19 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ARTÍCULOS CONFECCIONADOS DE MATERIAS TEXTILES, EXCEPTO PRENDAS DE VESTIR', 'SUB_RUB_COD' => 20 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE TAPICES Y ALFOMBRA', 'SUB_RUB_COD' => 20 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CUERDAS, CORDELES, BRAMANTES Y REDES', 'SUB_RUB_COD' => 20 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE TEJIDOS DE USO INDUSTRIAL COMO TEJIDOS IMPREGNADOS, MOLTOPRENE, BATISTA, ETC.', 'SUB_RUB_COD' => 20 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS TEXTILES N.C.P.', 'SUB_RUB_COD' => 20 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE TEJIDOS DE PUNTO', 'SUB_RUB_COD' => 21 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRENDAS DE VESTIR TEXTILES Y SIMILARES', 'SUB_RUB_COD' => 22 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRENDAS DE VESTIR DE CUERO NATURAL, ARTIFICIAL, PLÁSTICO', 'SUB_RUB_COD' => 22 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ACCESORIOS DE VESTIR', 'SUB_RUB_COD' => 22 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ROPA DE TRABAJO', 'SUB_RUB_COD' => 22 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADOBO Y TENIDOS DE PIELES; FABRICACIÓN DE ARTÍCULOS DE PIEL', 'SUB_RUB_COD' => 23 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CURTIDO Y ADOBO DE CUEROS', 'SUB_RUB_COD' => 23 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MALETAS, BOLSOS DE MANO Y SIMILARES; ARTÍCULOS DE TALABARTERÍA Y GUARNICIONERÍA', 'SUB_RUB_COD' => 23 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CALZADO', 'SUB_RUB_COD' => 24 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ASERRADO Y ACEPILLADURA DE MADERAS', 'SUB_RUB_COD' => 25 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE TABLEROS, PANELES Y HOJAS DE MADERA PARA ENCHAPADO', 'SUB_RUB_COD' => 26 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PARTES Y PIEZAS DE CARPINTERÍA PARA EDIFICIOS Y CONSTRUCCIONES', 'SUB_RUB_COD' => 26 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE RECIPIENTES DE MADERA', 'SUB_RUB_COD' => 26 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS DE MADERA; ARTÍCULOS DE CORCHO, PAJA Y MATERIALES TRENZABLES', 'SUB_RUB_COD' => 26 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CELULOSA Y OTRAS PASTAS DE MADERA', 'SUB_RUB_COD' => 27 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PAPEL DE PERIÓDICO', 'SUB_RUB_COD' => 27 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PAPEL Y CARTÓN N.C.P.', 'SUB_RUB_COD' => 27 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PAPEL Y CARTÓN ONDULADO Y DE ENVASES DE PAPEL Y CARTÓN', 'SUB_RUB_COD' => 27 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS ARTÍCULOS DE PAPEL Y CARTÓN', 'SUB_RUB_COD' => 27 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EDICIÓN PRINCIPALMENTE DE LIBROS', 'SUB_RUB_COD' => 28 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EDICIÓN DE FOLLETOS, PARTITURAS Y OTRAS PUBLICACIONES', 'SUB_RUB_COD' => 28 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EDICIÓN DE PERIÓDICOS, REVISTAS Y PUBLICACIONES PERIÓDICAS', 'SUB_RUB_COD' => 28 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EDICIÓN DE GRABACIONES', 'SUB_RUB_COD' => 28 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE EDICIÓN', 'SUB_RUB_COD' => 28 ]);
        App\Actividad::create([ 'ACT_DESC' => 'IMPRESIÓN PRINCIPALMENTE DE LIBROS', 'SUB_RUB_COD' => 29 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE IMPRESIÓN N.C.P.', 'SUB_RUB_COD' => 29 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE SERVICIO RELACIONADA CON LA IMPRESIÓN', 'SUB_RUB_COD' => 29 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPRODUCCIÓN DE GRABACIONES', 'SUB_RUB_COD' => 29 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE HORNOS COQUE', 'SUB_RUB_COD' => 30 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE REFINACIÓN DE PETRÓLEO', 'SUB_RUB_COD' => 30 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE COMBUSTIBLE NUCLEAR', 'SUB_RUB_COD' => 31 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CARBÓN VEGETAL, Y BRIQUETAS DE CARBÓN VEGETAL', 'SUB_RUB_COD' => 32 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE SUSTANCIAS QUÍMICAS BÁSICAS, EXCEPTO ABONOS Y COMPUESTOS DE NITRÓGENO', 'SUB_RUB_COD' => 32 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ABONOS Y COMPUESTOS DE NITRÓGENO', 'SUB_RUB_COD' => 32 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PLÁSTICOS EN FORMAS PRIMARIAS Y DE CAUCHO SINTÉTICO', 'SUB_RUB_COD' => 32 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PLAGUICIDAS Y OTROS PRODUCTOS QUÍMICOS DE USO AGROPECUARIO', 'SUB_RUB_COD' => 33 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PINTURAS, BARNICES Y PRODUCTOS DE REVESTIMIENTO SIMILARES', 'SUB_RUB_COD' => 33 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS FARMACEUTICOS, SUSTANCIAS QUÍMICAS MEDICINALES Y PRODUCTOS BOTÁNICOS', 'SUB_RUB_COD' => 33 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIONES DE JABONES Y DETERGENTES, PREPARADOS PARA LIMPIAR, PERFUMES Y PREPARADOS DE TOCADOR', 'SUB_RUB_COD' => 33 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE EXPLOSIVOS Y PRODUCTOS DE PIROTECNIA', 'SUB_RUB_COD' => 33 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS N.C.P.', 'SUB_RUB_COD' => 33 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE FIBRAS MANUFACTURADAS', 'SUB_RUB_COD' => 34 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CUBIERTAS Y CÁMARAS DE CAUCHO', 'SUB_RUB_COD' => 35 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECAUCHADO Y RENOVACIÓN DE CUBIERTAS DE CAUCHO', 'SUB_RUB_COD' => 35 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS DE CAUCHO', 'SUB_RUB_COD' => 35 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PLANCHAS, LÁMINAS, CINTAS, TIRAS DE PLÁSTICO', 'SUB_RUB_COD' => 36 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE TUBOS, MANGUERAS PARA LA CONSTRUCCIÓN', 'SUB_RUB_COD' => 36 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS ARTÍCULOS DE PLÁSTICO', 'SUB_RUB_COD' => 36 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN, MANIPULADO Y TRANSFORMACIÓN DE VIDRIO PLANO', 'SUB_RUB_COD' => 37 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE VIDRIO HUECO', 'SUB_RUB_COD' => 37 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE FIBRAS DE VIDRIO', 'SUB_RUB_COD' => 37 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ARTÍCULOS DE VIDRIO N.C.P.', 'SUB_RUB_COD' => 37 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE CERÁMICA NO REFRACTARIA PARA USO NO ESTRUCTURAL CON FINES ORNAMENTALES', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE CERÁMICA NO REFRACTARIA PARA USO NO ESTRUCTURAL N.C.P.', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE CERÁMICAS REFRACTARIA', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE ARCILLA Y CERÁMICAS NO REFRACTARIAS PARA USO ESTRUCTURAL', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CEMENTO, CAL Y YESO', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE HORMIGÓN, ARTÍCULOS DE HORMIGÓN Y MORTERO (MEZCLA PARA CONSTRUCCIÓN)', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS DE FIBROCEMENTO Y ASBESTOCEMENTO', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PANELES DE YESO PARA LA CONSTRUCCIÓN', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ARTÍCULOS DE CEMENTO Y YESO N.C.P.', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CORTE, TALLADO Y ACABADO DE LA PIEDRA', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MEZCLAS BITUMINOSAS A BASE DE ASFALTO, DE BETUNES NATURALES, Y PRODUCTOS SIMILARES', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS MINERALES NO METÁLICOS N.C.P', 'SUB_RUB_COD' => 38 ]);
        App\Actividad::create([ 'ACT_DESC' => 'INDUSTRIAS BASICAS DE HIERRO Y ACERO', 'SUB_RUB_COD' => 39 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE PRODUCTOS DE COBRE EN FORMAS PRIMARIAS.', 'SUB_RUB_COD' => 40 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ELABORACIÓN DE PRODUCTOS DE ALUMINIO EN FORMAS PRIMARIAS', 'SUB_RUB_COD' => 40 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y DE OTROS METALES NO FERROSOS N.C.P.', 'SUB_RUB_COD' => 40 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FUNDICIÓN DE HIERRO Y ACERO', 'SUB_RUB_COD' => 41 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FUNDICIÓN DE METALES NO FERROSOS', 'SUB_RUB_COD' => 41 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PRODUCTOS METÁLICOS DE USO ESTRUCTURAL', 'SUB_RUB_COD' => 42 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE RECIPIENTES DE GAS COMPRIMIDO O LICUADO', 'SUB_RUB_COD' => 42 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE TANQUES, DEPÓSITOS Y RECIPIENTES DE METAL N.C.P.', 'SUB_RUB_COD' => 42 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE TANQUES, DEPÓSITOS Y RECIPIENTES DE METAL', 'SUB_RUB_COD' => 42 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE GENERADORES DE VAPOR, EXCEPTO CALDERAS DE AGUA CALIENTE PARA CALEFACCIÓN', 'SUB_RUB_COD' => 42 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE GENERADORES DE VAPOR, EXCEPTO CALDERAS DE AGUA CALIENTE PARA CALEFACCIÓN CENTRAL', 'SUB_RUB_COD' => 42 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FORJA, PRENSADO, ESTAMPADO Y LAMINADO DE METAL; INCLUYE PULVIMETALURGIA', 'SUB_RUB_COD' => 43 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRATAMIENTOS Y REVESTIMIENTOS DE METALES; OBRAS DE INGENIERÍA MECÁNICA EN GENERAL', 'SUB_RUB_COD' => 43 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ARTÍCULOS DE CUCHILLERÍA', 'SUB_RUB_COD' => 43 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE HERRAMIENTAS DE MANO Y ARTÍCULOS DE FERRETERÍA', 'SUB_RUB_COD' => 43 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CABLES, ALAMBRES Y PRODUCTOS DE ALAMBRE', 'SUB_RUB_COD' => 43 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS ELABORADOS DE METAL N.C.P.', 'SUB_RUB_COD' => 43 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MOTORES Y TURBINAS, EXCEPTO PARA AERONAVES, VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MOTORES Y TURBINAS, EXCEPTO PARA AERONAVES, VEHÍCULOS AUTOMOTORES Y MOTOCICLETAS', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE BOMBAS, GRIFOS, VÁLVULAS, COMPRESORES, SISTEMAS HIDRÁULICOS', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE BOMBAS, COMPRESORES, SISTEMAS HIDRÁULICOS, VÁLVULAS Y ARTÍCULOS DE GRIFERÍA', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE COJINETES, ENGRANAJES, TRENES DE ENGRANAJES Y PIEZAS DE TRANSMISIÓN', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE COJINETES, ENGRANAJES, TRENES DE ENGRANAJES Y PIEZAS DE TRANSMISIÓN', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE HORNOS, HOGARES Y QUEMADORES', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE HORNOS, HOGARES Y QUEMADORES', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE EQUIPO DE ELEVACIÓN Y MANIPULACIÓN', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE EQUIPO DE ELEVACIÓN Y MANIPULACIÓN', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTRO TIPO DE MAQUINARIAS DE USO GENERAL', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN OTROS TIPOS DE MAQUINARIA Y EQUIPOS DE USO GENERAL', 'SUB_RUB_COD' => 44 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MÁQUINAS HERRAMIENTAS', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MÁQUINAS HERRAMIENTAS', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MAQUINARIA METALÚRGICA', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MAQUINARIA PARA LA INDUSTRIA METALÚRGICA', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MAQUINARIA PARA MINAS Y CANTERAS Y PARA OBRAS DE CONSTRUCCIÓN', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PARTES PARA MÁQUINAS DE SONDEO O PERFORACIÓN', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MAQUINARIA PARA LA EXPLOTACIÓN DE PETRÓLEO, MINAS, CANTERAS, Y OBRAS DE CONSTRUCCIÓN', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACOS', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACOS', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE PRENDAS TEXTILES, PRENDAS DE VESTIR Y CUEROS', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MAQUINARIA PARA LA INDUSTRIA TEXTIL, DE LA CONFECCIÓN, DEL CUERO Y DEL CALZADO', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ARMAS Y MUNICIONES', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE ARMAS', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS TIPOS DE MAQUINARIAS DE USO ESPECIAL', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO ESPECIAL', 'SUB_RUB_COD' => 45 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE APARATOS DE USO DOMÉSTICO N.C.P.', 'SUB_RUB_COD' => 46 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN Y ARMADO DE COMPUTADORES Y HARDWARE EN GENERAL', 'SUB_RUB_COD' => 47 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MAQUINARIA DE OFICINA, CONTABILIDAD, N.C.P.', 'SUB_RUB_COD' => 47 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MOTORES, GENERADORES Y TRANSFORMADORES ELÉCTRICOS', 'SUB_RUB_COD' => 48 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MOTORES, GENERADORES Y TRANSFORMADORES ELÉCTRICOS', 'SUB_RUB_COD' => 48 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE APARATOS DE DISTRIBUCIÓN Y CONTROL', 'SUB_RUB_COD' => 49 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE APARATOS DE DISTRIBUCIÓN Y CONTROL', 'SUB_RUB_COD' => 49 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE HILOS Y CABLES AISLADOS', 'SUB_RUB_COD' => 50 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ACUMULADORES DE PILAS Y BATERÍAS PRIMARIAS', 'SUB_RUB_COD' => 51 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE LÁMPARAS Y EQUIPO DE ILUMINACIÓN', 'SUB_RUB_COD' => 52 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE EQUIPO DE ILUMINACIÓN', 'SUB_RUB_COD' => 52 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO N.C.P.', 'SUB_RUB_COD' => 53 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO N.C.P.', 'SUB_RUB_COD' => 53 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE COMPONENTES ELECTRÓNICOS', 'SUB_RUB_COD' => 54 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE COMPONENTES ELECTRÓNICOS', 'SUB_RUB_COD' => 54 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE TRANSMISORES DE RADIO Y TELEVISIÓN, APARATOS PARA TELEFONÍA Y TELEGRAFÍA CON HILOS', 'SUB_RUB_COD' => 55 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE TRANSMISORES DE RADIO Y TELEVISIÓN, APARATOS PARA TELEFONÍA Y TELEGRAFÍA CON HILOS', 'SUB_RUB_COD' => 55 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE RECEPTORES (RADIO Y TV; APARATOS DE GRABACIÓN Y REPRODUCCIÓN (AUDIO Y VIDEO)', 'SUB_RUB_COD' => 56 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE EQUIPO MÉDICO Y QUIRÚRGICO, Y DE APARATOS ORTOPÉDICOS', 'SUB_RUB_COD' => 57 ]);
        App\Actividad::create([ 'ACT_DESC' => 'LABORATORIOS DENTALES', 'SUB_RUB_COD' => 57 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE EQUIPO MÉDICO Y QUIRÚRGICO, Y DE APARATOS ORTOPÉDICOS', 'SUB_RUB_COD' => 57 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE INSTRUMENTOS Y APARATOS PARA MEDIR, VERIFICAR, ENSAYAR, NAVEGAR Y OTROS FINES', 'SUB_RUB_COD' => 57 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE INSTRUMENTOS Y APARATOS PARA MEDIR, VERIFICAR, ENSAYAR, NAVEGAR Y OTROS FINES', 'SUB_RUB_COD' => 57 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE EQUIPOS DE CONTROL DE PROCESOS INDUSTRIALES', 'SUB_RUB_COD' => 57 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE EQUIPOS DE CONTROL DE PROCESOS INDUSTRIALES', 'SUB_RUB_COD' => 57 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN Y/O REPARACIÓN DE LENTES Y ARTÍCULOS OFTALMOLÓGICOS', 'SUB_RUB_COD' => 58 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE INSTRUMENTOS DE OPTICA N.C.P. Y EQUIPOS FOTOGRÁFICOS', 'SUB_RUB_COD' => 58 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE INSTRUMENTOS DE OPTICA N.C.P Y EQUIPO FOTOGRÁFICOS', 'SUB_RUB_COD' => 58 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE RELOJES', 'SUB_RUB_COD' => 59 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE VEHÍCULOS AUTOMOTORES', 'SUB_RUB_COD' => 60 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE CARROCERÍAS PARA VEHÍCULOS AUTOMOTORES; FABRICACIÓN DE REMOLQUES Y SEMI REMOLQUES', 'SUB_RUB_COD' => 60 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PARTES Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES Y SUS MOTORES', 'SUB_RUB_COD' => 60 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONSTRUCCIÓN Y REPARACIÓN DE BUQUES; ASTILLEROS', 'SUB_RUB_COD' => 61 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONSTRUCCIÓN DE EMBARCACIONES MENORES', 'SUB_RUB_COD' => 61 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE EMBARCACIONES MENORES', 'SUB_RUB_COD' => 61 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONSTRUCCIÓN DE EMBARCACIONES DE RECREO Y DEPORTE', 'SUB_RUB_COD' => 61 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE EMBARCACIONES DE RECREO Y DEPORTES', 'SUB_RUB_COD' => 61 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE LOCOMOTORAS Y DE MATERIAL RODANTE PARA FERROCARRILES Y TRANVÍAS', 'SUB_RUB_COD' => 62 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE AERONAVES Y NAVES ESPACIALES', 'SUB_RUB_COD' => 63 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE AERONAVES Y NAVES ESPACIALES', 'SUB_RUB_COD' => 63 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MOTOCICLETAS', 'SUB_RUB_COD' => 64 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE BICICLETAS Y DE SILLONES DE RUEDAS PARA INVALIDOS', 'SUB_RUB_COD' => 64 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS EQUIPOS DE TRANSPORTE N.C.P.', 'SUB_RUB_COD' => 64 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE MUEBLES PRINCIPALMENTE DE MADERA', 'SUB_RUB_COD' => 65 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE OTROS MUEBLES N.C.P., INCLUSO COLCHONES', 'SUB_RUB_COD' => 65 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE JOYAS Y PRODUCTOS CONEXOS', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE INSTRUMENTOS DE MÚSICA', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ARTÍCULOS DE DEPORTE', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE JUEGOS Y JUGUETES', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE PLUMAS Y LÁPICES DE TODA CLASE Y ARTÍCULOS DE ESCRITORIO EN GENERAL', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE BROCHAS, ESCOBAS Y CEPILLOS', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE FÓSFOROS', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE ARTÍCULOS DE OTRAS INDUSTRIAS N.C.P.', 'SUB_RUB_COD' => 66 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECICLAMIENTO DE DESPERDICIOS Y DESECHOS METÁLICOS', 'SUB_RUB_COD' => 67 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECICLAMIENTO DE PAPEL', 'SUB_RUB_COD' => 67 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECICLAMIENTO DE VIDRIO', 'SUB_RUB_COD' => 67 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECICLAMIENTO DE OTROS DESPERDICIOS Y DESECHOS N.C.P.', 'SUB_RUB_COD' => 67 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GENERACIÓN HIDROELÉCTRICA', 'SUB_RUB_COD' => 68 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GENERACIÓN EN CENTRALES TERMOELÉCTRICA DE CICLOS COMBINADOS', 'SUB_RUB_COD' => 68 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GENERACIÓN EN OTRAS CENTRALES TERMOELÉCTRICAS', 'SUB_RUB_COD' => 68 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GENERACIÓN EN OTRAS CENTRALES N.C.P.', 'SUB_RUB_COD' => 68 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSMISIÓN DE ENERGÍA ELÉCTRICA', 'SUB_RUB_COD' => 68 ]);
        App\Actividad::create([ 'ACT_DESC' => 'DISTRIBUCIÓN DE ENERGIA ELÉCTRICA', 'SUB_RUB_COD' => 68 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FABRICACIÓN DE GAS; DISTRIBUCIÓN DE COMBUSTIBLES GASEOSOS POR TUBERÍAS', 'SUB_RUB_COD' => 69 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SUMINISTRO DE VAPOR Y AGUA CALIENTE', 'SUB_RUB_COD' => 70 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CAPTACIÓN, DEPURACIÓN Y DISTRIBUCIÓN DE AGUA', 'SUB_RUB_COD' => 71 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PREPARACIÓN DEL TERRENO, EXCAVACIONES Y MOVIMIENTOS DE TIERRAS', 'SUB_RUB_COD' => 72 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE DEMOLICIÓN Y EL DERRIBO DE EDIFICIOS Y OTRAS ESTRUCTURAS', 'SUB_RUB_COD' => 72 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONSTRUCCIÓN DE EDIFICIOS COMPLETOS O DE PARTES DE EDIFICIOS', 'SUB_RUB_COD' => 72 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OBRAS DE INGENIERÍA', 'SUB_RUB_COD' => 72 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACONDICIONAMIENTO DE EDIFICIOS', 'SUB_RUB_COD' => 72 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OBRAS MENORES EN CONSTRUCCIÓN (CONTRATISTAS, ALBANILES, CARPINTEROS)', 'SUB_RUB_COD' => 72 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE EQUIPO DE CONSTRUCCIÓN O DEMOLICIÓN DOTADO DE OPERARIOS', 'SUB_RUB_COD' => 72 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE VEHÍCULOS AUTOMOTORES (IMPORTACIÓN, DISTRIBUCIÓN) EXCEPTO MOTOCICLETAS', 'SUB_RUB_COD' => 73 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA O COMPRAVENTA AL POR MENOR DE VEHÍCULOS AUTOMOTORES NUEVOS O USADOS; EXCEPTO MOTOCICLETAS', 'SUB_RUB_COD' => 73 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIO DE LAVADO DE VEHÍCULOS AUTOMOTORES', 'SUB_RUB_COD' => 74 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE REMOLQUE DE VEHÍCULOS (GRUAS)', 'SUB_RUB_COD' => 74 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MANTENIMIENTO Y REPARACIÓN DE VEHÍCULOS AUTOMOTORES', 'SUB_RUB_COD' => 74 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA DE PARTES, PIEZAS Y ACCESORIOS DE VEHÍCULOS AUTOMOTORES', 'SUB_RUB_COD' => 75 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA DE MOTOCICLETAS', 'SUB_RUB_COD' => 76 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA DE PIEZAS Y ACCESORIOS DE MOTOCICLETAS', 'SUB_RUB_COD' => 76 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE MOTOCICLETAS', 'SUB_RUB_COD' => 76 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE COMBUSTIBLE PARA AUTOMOTORES', 'SUB_RUB_COD' => 77 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CORRETAJE DE PRODUCTOS AGRÍCOLAS', 'SUB_RUB_COD' => 78 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CORRETAJE DE GANADO (FERIAS DE GANADO)', 'SUB_RUB_COD' => 78 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS TIPOS DE CORRETAJES O REMATES N.C.P. (NO INCLUYE SERVICIOS DE MARTILLERO)', 'SUB_RUB_COD' => 78 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE ANIMALES VIVOS', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE PRODUCTOS PECUARIOS (LANAS, PIELES, CUEROS SIN PROCESAR]); EXCEPTO ALIMENTOS', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MATERIAS PRIMAS AGRÍCOLAS', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MAYORISTA DE FRUTAS Y VERDURAS', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MAYORISTAS DE CARNES', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MAYORISTAS DE PRODUCTOS DEL MAR (PESCADO, MARISCOS, ALGAS)', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MAYORISTAS DE VINOS Y BEBIDAS ALCOHÓLICAS Y DE FANTASÍA', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE CONFITES', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE TABACO Y PRODUCTOS DERIVADOS', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE HUEVOS, LECHE, ABARROTES, Y OTROS ALIMENTOS N.C.P.', 'SUB_RUB_COD' => 79 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MUEBLES', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE ARTÍCULOS ELÉCTRICOS Y ELECTRÓNICOS PARA EL HOGAR', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE ARTÍCULOS DE PERFUMERÍA, COSMÉTICOS, JABONES Y PRODUCTOS DE LIMPIEZA', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE PAPEL Y CARTÓN', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE LIBROS', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE REVISTAS Y PERIÓDICOS', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE PRODUCTOS FARMACEUTICOS', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE INSTRUMENTOS CIENTÍFICOS Y QUIRÚRGICOS', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE OTROS ENSERES DOMÉSTICOS N.C.P.', 'SUB_RUB_COD' => 80 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE COMBUSTIBLES LÍQUIDOS', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE COMBUSTIBLES SÓLIDOS', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE COMBUSTIBLES GASEOSOS', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE PRODUCTOS CONEXOS A LOS COMBUSTIBLES', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE METALES Y MINERALES METALÍFEROS', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MADERA NO TRABAJADA Y PRODUCTOS RESULTANTES DE SU ELABORACIÓN PRIMARIA', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MATERIALES DE CONSTRUCCIÓN, ARTÍCULOS DE FERRETERÍA Y RELACIONADOS', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE PRODUCTOS QUÍMICOS', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE DESECHOS METÁLICOS (CHATARRA)', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE INSUMOS VETERINARIOS', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE OTROS PRODUCTOS INTERMEDIOS, DESPERDICIOS Y DESECHOS N.C.P.', 'SUB_RUB_COD' => 81 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA AGRÍCOLA Y FORESTAL', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA METALÚRGICA', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA PARA LA MINERÍA', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA PARA LA CONSTRUCCIÓN', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA PARA TEXTILES Y CUEROS', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MÁQUINAS Y EQUIPOS DE OFICINA; INCLUYE MATERIALES CONEXOS', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA Y EQUIPO DE TRANSPORTE EXCEPTO VEHÍCULOS AUTOMOTORES', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MAYOR DE MAQUINARIA, HERRAMIENTAS, EQUIPO Y MATERIALES N.C.P.', 'SUB_RUB_COD' => 82 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GRANDES ESTABLECIMIENTOS VENTA DE ALIMENTOS; HIPERMERCADOS', 'SUB_RUB_COD' => 83 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALMACENES MEDIANOS VENTA DE ALIMENTOS; SUPERMERCADOS, MINIMARKETS', 'SUB_RUB_COD' => 83 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALMACENES PEQUENOS VENTA DE ALIMENTOS', 'SUB_RUB_COD' => 83 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GRANDES TIENDAS - PRODUCTOS DE FERRETERÍA Y PARA EL HOGAR', 'SUB_RUB_COD' => 83 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GRANDES TIENDAS - VESTUARIO Y PRODUCTOS PARA EL HOGAR', 'SUB_RUB_COD' => 83 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE OTROS PRODUCTOS EN PEQUENOS ALMACENES NO ESPECIALIZADOS', 'SUB_RUB_COD' => 83 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE BEBIDAS Y LICORES (BOTILLERÍAS)', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE CARNES (ROJAS, BLANCAS, OTRAS) PRODUCTOS CÁRNICOS Y SIMILARES', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE VERDURAS Y FRUTAS (VERDULERÍA)', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE PESCADOS, MARISCOS Y PRODUCTOS CONEXOS', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE PRODUCTOS DE PANADERÍA Y PASTELERÍA', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE ALIMENTOS PARA MASCOTAS Y ANIMALES EN GENERAL', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE AVES Y HUEVOS', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE PRODUCTOS DE CONFITERÍAS, CIGARRILLOS, Y OTROS', 'SUB_RUB_COD' => 84 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FARMACIAS - PERTENECIENTES A CADENA DE ESTABLECIMIENTOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FARMACIAS INDEPENDIENTES', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE PRODUCTOS MEDICINALES', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE ARTÍCULOS ORTOPÉDICOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE ARTÍCULOS DE TOCADOR Y COSMÉTICOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE CALZADO', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE PRENDAS DE VESTIR EN GENERAL, INCLUYE ACCESORIOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE LANAS, HILOS Y SIMILARES', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE MALETERÍAS, TALABARTERÍAS Y ARTÍCULOS DE CUERO', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE ROPA INTERIOR Y PRENDAS DE USO PERSONAL', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE TEXTILES PARA EL HOGAR Y OTROS PRODUCTOS TEXTILES N.C.P.', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE ARTÍCULOS ELECTRODOMÉSTICOS Y ELECTRÓNICOS PARA EL HOGAR', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE CRISTALES, LOZAS, PORCELANA, MENAJE (CRISTALERÍAS)', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE MUEBLES; INCLUYE COLCHONES', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE INSTRUMENTOS MUSICALES (CASA DE MÚSICA)', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE DISCOS, CASSETTES, DVD Y VIDEOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE LÁMPARAS, APLIQUÉS Y SIMILARES', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE APARATOS, ARTÍCULOS, EQUIPO DE USO DOMÉSTICO N.C.P.', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE ARTÍCULOS DE FERRETERÍA Y MATERIALES DE CONSTRUCCIÓN', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE PINTURAS, BARNICES Y LACAS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE PRODUCTOS DE VIDRIO', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ARTÍCULOS FOTOGRÁFICOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ARTÍCULOS ÓPTICOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO POR MENOR DE JUGUETES', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE LIBROS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE REVISTAS Y DIARIOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO DE ARTÍCULOS DE SUMINISTROS DE OFICINAS Y ARTÍCULOS DE ESCRITORIO EN GENERAL', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE COMPUTADORAS, SOFTWARES Y SUMINISTROS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ARMERÍAS, ARTÍCULOS DE CAZA Y PESCA', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE BICICLETAS Y SUS REPUESTOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ARTÍCULOS DEPORTIVOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ARTÍCULOS DE JOYERÍA, FANTASÍAS Y RELOJERÍAS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE GAS LICUADO EN BOMBONAS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE CARBÓN, LENA Y OTROS COMBUSTIBLES DE USO DOMÉSTICO', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ARTÍCULOS TÍPICOS (ARTESANÍAS)', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE FLORES, PLANTAS, ÁRBOLES, SEMILLAS, ABONOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR DE MASCOTAS Y ACCESORIOS', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTAS AL POR MENOR DE OTROS PRODUCTOS EN ALMACENES ESPECIALIZADOS N.C.P.', 'SUB_RUB_COD' => 85 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ANTIGUEDADES', 'SUB_RUB_COD' => 86 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ROPA USADA', 'SUB_RUB_COD' => 86 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMERCIO AL POR MENOR DE ARTÍCULOS Y ARTEFACTOS USADOS N.C.P.', 'SUB_RUB_COD' => 86 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR EN EMPRESAS DE VENTA A DISTANCIA POR CORREO', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR EN EMPRESAS DE VENTA A DISTANCIA VÍA TELEFÓNICA', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR EN EMPRESAS DE VENTA A DISTANCIA VÍA INTERNET; COMERCIO ELECTRÓNICO', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR EN PUESTOS DE VENTA Y MERCADOS', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR REALIZADA POR INDEPENDIENTES EN TRANSPORTE PÚBLICO (LEY 20.388)', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR NO REALIZADA EN ALMACENES DE PRODUCTOS PROPIOS N.C.P.', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MÁQUINAS EXPENDEDORAS', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'VENTA AL POR MENOR A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS TIPOS DE VENTA AL POR MENOR NO REALIZADA EN ALMACENES N.C.P.', 'SUB_RUB_COD' => 87 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE CALZADO Y OTROS ARTÍCULOS DE CUERO', 'SUB_RUB_COD' => 88 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIONES ELÉCTRICAS Y ELECTRÓNICAS', 'SUB_RUB_COD' => 88 ]);
        App\Actividad::create([ 'ACT_DESC' => 'REPARACIÓN DE RELOJES Y JOYAS', 'SUB_RUB_COD' => 88 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS REPARACIONES DE EFECTOS PERSONALES Y ENSERES DOMÉSTICOS N.C.P.', 'SUB_RUB_COD' => 88 ]);
        App\Actividad::create([ 'ACT_DESC' => 'HOTELES', 'SUB_RUB_COD' => 89 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MOTELES', 'SUB_RUB_COD' => 89 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RESIDENCIALES', 'SUB_RUB_COD' => 89 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS TIPOS DE HOSPEDAJE TEMPORAL COMO CAMPING, ALBERGUES, POSADAS, REFUGIOS Y SIMILARES', 'SUB_RUB_COD' => 89 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RESTAURANTES', 'SUB_RUB_COD' => 90 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS DE COMIDA RÁPIDA (BARES, FUENTES DE SODA, GELATERÍAS, PIZZERÍAS Y SIMILARES)', 'SUB_RUB_COD' => 90 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CASINOS Y CLUBES SOCIALES', 'SUB_RUB_COD' => 90 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE COMIDA PREPARADA EN FORMA INDUSTRIAL', 'SUB_RUB_COD' => 90 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE BANQUETES, BODAS Y OTRAS CELEBRACIONES', 'SUB_RUB_COD' => 90 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE OTROS ESTABLECIMIENTOS QUE EXPENDEN COMIDAS Y BEBIDAS', 'SUB_RUB_COD' => 90 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE INTERURBANO DE PASAJEROS POR FERROCARRILES', 'SUB_RUB_COD' => 91 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE DE CARGA POR FERROCARRILES', 'SUB_RUB_COD' => 91 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE URBANO DE PASAJEROS VÍA FERROCARRIL (INCLUYE METRO)', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE URBANO DE PASAJEROS VÍA AUTOBUS (LOCOMOCIÓN COLECTIVA)', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE INTERURBANO DE PASAJEROS VÍA AUTOBUS', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE URBANO DE PASAJEROS VÍA TAXI COLECTIVO', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE TRANSPORTE ESCOLAR', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE TRANSPORTE DE TRABAJADORES', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS TIPOS DE TRANSPORTE REGULAR DE PASAJEROS POR VÍA TERRESTRE N.C.P.', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTES POR TAXIS LIBRES Y RADIOTAXIS', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE TRANSPORTE A TURISTAS', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE DE PASAJEROS EN VEHÍCULOS DE TRACCIÓN HUMANA Y ANIMAL', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS TIPOS DE TRANSPORTE NO REGULAR DE PASAJEROS N.C.P.', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE DE CARGA POR CARRETERA', 'SUB_RUB_COD' => 92 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE POR TUBERÍAS', 'SUB_RUB_COD' => 93 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE MARÍTIMO Y DE CABOTAJE DE PASAJEROS', 'SUB_RUB_COD' => 94 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE MARÍTIMO Y DE CABOTAJE DE CARGA', 'SUB_RUB_COD' => 94 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE DE PASAJEROS POR VÍAS DE NAVEGACIÓN INTERIORES', 'SUB_RUB_COD' => 95 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE DE CARGA POR VÍAS DE NAVEGACIÓN INTERIORES', 'SUB_RUB_COD' => 95 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE REGULAR POR VÍA AÉREA DE PASAJEROS', 'SUB_RUB_COD' => 96 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE REGULAR POR VÍA AÉREA DE CARGA', 'SUB_RUB_COD' => 96 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE NO REGULAR POR VÍA AÉREA DE PASAJEROS', 'SUB_RUB_COD' => 96 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE NO REGULAR POR VÍA AÉREA DE CARGA', 'SUB_RUB_COD' => 96 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MANIPULACIÓN DE LA CARGA', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE ALMACENAMIENTO Y DEPÓSITO', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TERMINALES TERRESTRES DE PASAJEROS', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTACIONAMIENTO DE VEHÍCULOS Y PARQUÍMETROS', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PUERTOS Y AEROPUERTOS', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PRESTADOS POR CONCESIONARIOS DE CARRETERAS', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES CONEXAS AL TRANSPORTE N.C.P.', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENCIAS Y ORGANIZADORES DE VIAJES; ACTIVIDADES DE ASISTENCIA A TURISTAS N.C.P.', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENCIAS DE ADUANAS', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENCIAS DE TRANSPORTE', 'SUB_RUB_COD' => 97 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES POSTALES NACIONALES', 'SUB_RUB_COD' => 98 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE CORREO DISTINTAS DE LAS ACTIVIDADES POSTALES NACIONALES', 'SUB_RUB_COD' => 98 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE TELEFONÍA FIJA', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE TELEFONÍA MÓVIL', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PORTADORES TELEFÓNICOS (LARGA DISTANCIA NACIONAL E INTERNACIONAL)', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE TELEVISIÓN NO ABIERTA', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PROVEEDORES DE INTERNET', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CENTROS DE LLAMADOS; INCLUYE ENVÍO DE FAX', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CENTROS DE ACCESO A INTERNET', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS SERVICIOS DE TELECOMUNICACIONES N.C.P.', 'SUB_RUB_COD' => 99 ]);
        App\Actividad::create([ 'ACT_DESC' => 'BANCA CENTRAL', 'SUB_RUB_COD' => 100 ]);
        App\Actividad::create([ 'ACT_DESC' => 'BANCOS', 'SUB_RUB_COD' => 100 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FINANCIERAS', 'SUB_RUB_COD' => 100 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS TIPOS DE INTERMEDIACIÓN MONETARIA N.C.P.', 'SUB_RUB_COD' => 100 ]);
        App\Actividad::create([ 'ACT_DESC' => 'LEASING FINANCIERO', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'LEASING HABITACIONAL', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FINANCIAMIENTO DEL FOMENTO DE LA PRODUCCIÓN', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE CRÉDITO PRENDARIO', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FACTORING', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SECURITIZADORAS', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS INSTITUCIONES FINANCIERAS N.C.P.', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADMINISTRADORAS DE FONDOS DE INVERSIÓN', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADMINISTRADORAS DE FONDOS MUTUOS', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADMINISTRADORAS DE FICES (FONDOS DE INVERSIÓN DE CAPITAL EXTRANJERO)', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADMINISTRADORAS DE FONDOS PARA LA VIVIENDA', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADMINISTRADORAS DE FONDOS PARA OTROS FINES Y/O GENERALES', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SOCIEDADES DE INVERSIÓN Y RENTISTAS DE CAPITALES MOBILIARIOS EN GENERAL', 'SUB_RUB_COD' => 101 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADMINISTRACIÓN DE MERCADOS FINANCIEROS', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CORREDORES DE BOLSA', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENTES DE VALORES', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS SERVICIOS DE CORRETAJE', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CÁMARA DE COMPENSACIÓN', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ADMINISTRADORA DE TARJETAS DE CRÉDITO', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE ASESORÍA, CONSULTORÍA FINANCIERA Y DE APOYO AL GIRO', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CLASIFICADORES DE RIESGOS', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CASAS DE CAMBIO Y OPERADORES DE DIVISA', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES AUXILIARES DE LA INTERMEDIACIÓN FINANCIERA N.C.P.', 'SUB_RUB_COD' => 102 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CORREDORES DE SEGUROS', 'SUB_RUB_COD' => 103 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENTES Y LIQUIDADORES DE SEGUROS', 'SUB_RUB_COD' => 103 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES AUXILIARES DE LA FINANCIACIÓN DE PLANES DE SEGUROS Y DE PENSIONES N.C.P.', 'SUB_RUB_COD' => 103 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ARRIENDO DE INMUEBLES AMOBLADOS O CON EQUIPOS Y MAQUINARIAS', 'SUB_RUB_COD' => 104 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COMPRA, VENTA Y ALQUILER (EXCEPTO AMOBLADOS) DE INMUEBLES PROPIOS O ARRENDADOS', 'SUB_RUB_COD' => 104 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CORREDORES DE PROPIEDADES', 'SUB_RUB_COD' => 105 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE AUTOS Y CAMIONETAS SIN CHOFER', 'SUB_RUB_COD' => 106 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE OTROS EQUIPOS DE TRANSPORTE POR VÍA TERRESTRE SIN OPERARIOS', 'SUB_RUB_COD' => 106 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE TRANSPORTE POR VÍA ACUÁTICA SIN TRIPULACIÓN', 'SUB_RUB_COD' => 106 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE EQUIPO DE TRANSPORTE POR VÍA AÉREA SIN TRIPULANTES', 'SUB_RUB_COD' => 106 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE MAQUINARIA Y EQUIPO AGROPECUARIO', 'SUB_RUB_COD' => 107 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE MAQUINARIA Y EQUIPO DE CONSTRUCCIÓN E INGENIERÍA CIVIL', 'SUB_RUB_COD' => 107 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE MAQUINARIA Y EQUIPO DE OFICINA (SIN OPERARIOS NI SERVICIO ADMINISTRATIVO)', 'SUB_RUB_COD' => 107 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE OTROS TIPOS DE MAQUINARIAS Y EQUIPOS N.C.P.', 'SUB_RUB_COD' => 107 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE BICICLETAS Y ARTÍCULOS PARA DEPORTES', 'SUB_RUB_COD' => 108 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ARRIENDO DE VIDEOS, JUEGOS DE VIDEO, Y EQUIPOS REPRODUCTORES DE VIDEO, MÚSICA Y SIMILARES', 'SUB_RUB_COD' => 108 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE MOBILIARIO PARA EVENTOS (SILLAS, MESAS, MESONES, VAJILLAS, TOLDOS Y RELACIONADOS)', 'SUB_RUB_COD' => 108 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ALQUILER DE OTROS EFECTOS PERSONALES Y ENSERES DOMÉSTICOS N.C.P.', 'SUB_RUB_COD' => 108 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ASESORES Y CONSULTORES EN INFORMÁTICA (SOFTWARE)', 'SUB_RUB_COD' => 109 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PROCESAMIENTO DE DATOS Y ACTIVIDADES RELACIONADAS CON BASES DE DATOS', 'SUB_RUB_COD' => 109 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE SERVICIOS INTEGRALES DE INFORMÁTICA', 'SUB_RUB_COD' => 109 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MANTENIMIENTO Y REPARACIÓN DE MAQUINARIA DE OFICINA, CONTABILIDAD E INFORMÁTICA', 'SUB_RUB_COD' => 110 ]);
        App\Actividad::create([ 'ACT_DESC' => 'INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS NATURALES Y LA INGENIERÍA', 'SUB_RUB_COD' => 111 ]);
        App\Actividad::create([ 'ACT_DESC' => 'INVESTIGACIONES Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS SOCIALES Y LAS HUMANIDADES', 'SUB_RUB_COD' => 111 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS JURÍDICOS', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIO NOTARIAL', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONSERVADOR DE BIENES RAICES', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECEPTORES JUDICIALES', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ARBITRAJES, SÍNDICOS, PERITOS Y OTROS', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE CONTABILIDAD, TENEDURÍA DE LIBROS Y AUDITORÍA; ASESORAMIENTOS TRIBUTARIOS', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'INVESTIGACIÓN DE MERCADOS Y REALIZACIÓN DE ENCUESTAS DE OPINIÓN PÚBLICA', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE ASESORAMIENTO EMPRESARIAL Y EN MATERIA DE GESTIÓN', 'SUB_RUB_COD' => 112 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE ARQUITECTURA Y TÉCNICO RELACIONADO', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE SERVICIOS GEOLÓGICOS Y DE PROSPECCIÓN', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PROFESIONALES EN GEOLOGÍA Y PROSPECCIÓN', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE SERVICIOS DE TOPOGRAFÍA Y AGRIMENSURA', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PROFESIONALES DE TOPOGRAFÍA Y AGRIMENSURA', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE INGENIERÍA PRESTADOS POR EMPRESAS N.C.P.', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE INGENIERÍA PRESTADOS POR PROFESIONALES N.C.P.', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS SERVICIOS DESARROLLADOS POR PROFESIONALES', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIO DE REVISIÓN TÉCNICA DE VEHÍCULOS AUTOMOTORES', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS SERVICIOS DE ENSAYOS Y ANALISIS TÉCNICOS', 'SUB_RUB_COD' => 113 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE PUBLICIDAD', 'SUB_RUB_COD' => 114 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PERSONALES EN PUBLICIDAD', 'SUB_RUB_COD' => 114 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS SUMINISTRO DE PERSONAL; EMPRESAS SERVICIOS TRANSITORIOS', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE RECLUTAMIENTO DE PERSONAL', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE INVESTIGACIÓN', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS INTEGRALES DE SEGURIDAD', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'TRANSPORTE DE VALORES', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PERSONALES RELACIONADOS CON SEGURIDAD', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE LIMPIEZA DE EDIFICIOS RESIDENCIALES Y NO RESIDENCIALES', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'DESRATIZACIÓN Y FUMIGACIÓN NO AGRÍCOLA', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE REVELADO, IMPRESIÓN, AMPLIACIÓN DE FOTOGRAFÍAS', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE FOTOGRAFÍA PUBLICITARIA', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PERSONALES DE FOTOGRAFÍA', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE ENVASADO Y EMPAQUE', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE COBRANZA DE CUENTAS', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EVALUACIÓN Y CALIFICACIÓN DEL GRADO DE SOLVENCIA', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ASESORÍAS EN LA GESTIÓN DE LA COMPRA O VENTA DE PEQUENAS Y MEDIANAS EMPRESAS', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'DISENADORES DE VESTUARIO', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'DISENADORES DE INTERIORES', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS DISENADORES N.C.P.', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE TAQUIGRAFÍA, REPRODUCCIÓN, DESPACHO DE CORRESPONDENCIA, Y OTRAS LABORES DE OFICINA', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PERSONALES DE TRADUCCIÓN, INTERPRETACIÓN Y LABORES DE OFICINA', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EMPRESAS DE TRADUCCIÓN E INTERPRETACIÓN', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE FOTOCOPIAS', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENCIAS DE CONTRATACIÓN DE ACTORES', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE SUBASTA (MARTILLEROS)', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GALERÍAS DE ARTE', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FERIAS DE EXPOSICIONES CON FINES EMPRESARIALES', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE CONTESTACIÓN DE LLAMADAS (CALL CENTER)', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES EMPRESARIALES N.C.P.', 'SUB_RUB_COD' => 115 ]);
        App\Actividad::create([ 'ACT_DESC' => 'GOBIERNO CENTRAL', 'SUB_RUB_COD' => 116 ]);
        App\Actividad::create([ 'ACT_DESC' => 'MUNICIPALIDADES', 'SUB_RUB_COD' => 116 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DEL PODER JUDICIAL', 'SUB_RUB_COD' => 116 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DEL PODER LEGISLATIVO', 'SUB_RUB_COD' => 116 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RELACIONES EXTERIORES', 'SUB_RUB_COD' => 116 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE DEFENSA', 'SUB_RUB_COD' => 116 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE MANTENIMIENTO DEL ORDEN PÚBLICO Y DE SEGURIDAD', 'SUB_RUB_COD' => 116 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA RELACIONADOS CON SALUD', 'SUB_RUB_COD' => 117 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CAJAS DE COMPENSACIÓN', 'SUB_RUB_COD' => 117 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA', 'SUB_RUB_COD' => 117 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS DE ENSEÑANZA PREESCOLAR', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS DE ENSEÑANZA PRIMARIA', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS DE ENSEÑANZA SECUNDARIA DE FORMACIÓN GENERAL', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS DE ENSEÑANZA SECUNDARIA DE FORMACIÓN TÉCNICA Y PROFESIONAL', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'UNIVERSIDADES', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'INSTITUTOS PROFESIONALES', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CENTROS DE FORMACIÓN TÉCNICA', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS DE ENSEÑANZA PRIMARIA Y SECUNDARIA PARA ADULTOS', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS DE ENSEÑANZA PREUNIVERSITARIA', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EDUCACIÓN EXTRAESCOLAR (ESCUELA DE CONDUCCIÓN, MÚSICA, MODELAJE, ETC.)', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EDUCACIÓN A DISTANCIA (INTERNET, CORRESPONDENCIA, OTRAS)', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PERSONALES DE EDUCACIÓN', 'SUB_RUB_COD' => 118 ]);
        App\Actividad::create([ 'ACT_DESC' => 'HOSPITALES Y CLÍNICAS', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CLÍNICAS PSIQUIATRICAS, CENTROS DE REHABILITACIÓN, ASILOS Y CLÍNICAS DE REPOSO', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE MÉDICOS EN FORMA INDEPENDIENTE', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESTABLECIMIENTOS MÉDICOS DE ATENCIÓN AMBULATORIA (CENTROS MÉDICOS)', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE ODONTÓLOGOS EN FORMA INDEPENDIENTE', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CENTROS DE ATENCIÓN ODONTOLÓGICA', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'LABORATORIOS CLÍNICOS; INCLUYE BANCOS DE SANGRE', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS PROFESIONALES DE LA SALUD', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES EMPRESARIALES RELACIONADAS CON LA SALUD HUMANA', 'SUB_RUB_COD' => 119 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE CLÍNICAS VETERINARIAS', 'SUB_RUB_COD' => 120 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE MÉDICOS VETERINARIOS EN FORMA INDEPENDIENTE', 'SUB_RUB_COD' => 120 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE OTROS PROFESIONALES INDEPENDIENTES EN EL ÁREA VETERINARIA', 'SUB_RUB_COD' => 120 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS SOCIALES CON ALOJAMIENTO', 'SUB_RUB_COD' => 121 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS SOCIALES SIN ALOJAMIENTO', 'SUB_RUB_COD' => 121 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE VERTEDEROS', 'SUB_RUB_COD' => 122 ]);
        App\Actividad::create([ 'ACT_DESC' => 'BARRIDO DE EXTERIORES', 'SUB_RUB_COD' => 122 ]);
        App\Actividad::create([ 'ACT_DESC' => 'RECOGIDA Y ELIMINACIÓN DE DESECHOS', 'SUB_RUB_COD' => 122 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE EVACUACIÓN DE RILES Y AGUAS SERVIDAS', 'SUB_RUB_COD' => 122 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE TRATAMIENTO DE RILES Y AGUAS SERVIDAS', 'SUB_RUB_COD' => 122 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE MANEJO DE DESPERDICIOS', 'SUB_RUB_COD' => 122 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE ORGANIZACIONES EMPRESARIALES Y DE EMPLEADORES', 'SUB_RUB_COD' => 123 ]);
        App\Actividad::create([ 'ACT_DESC' => 'COLEGIOS PROFESIONALES', 'SUB_RUB_COD' => 123 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE OTRAS ORGANIZACIONES PROFESIONALES', 'SUB_RUB_COD' => 123 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE SINDICATOS', 'SUB_RUB_COD' => 124 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE ORGANIZACIONES RELIGIOSAS', 'SUB_RUB_COD' => 124 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE ORGANIZACIONES POLÍTICAS', 'SUB_RUB_COD' => 124 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CENTROS DE MADRES Y UNIDADES VECINALES Y COMUNALES', 'SUB_RUB_COD' => 124 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CLUBES SOCIALES', 'SUB_RUB_COD' => 124 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE INSTITUTOS DE ESTUDIOS, FUNDACIONES, CORPORACIONES DE DESARROLLO (EDUCACIÓN, SALUD)', 'SUB_RUB_COD' => 124 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE OTRAS ASOCIACIONES N.C.P.', 'SUB_RUB_COD' => 124 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PRODUCCIÓN DE PELÍCULAS CINEMATOGRÁFICAS', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'DISTRIBUIDORA CINEMATOGRÁFICAS', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXHIBICIÓN DE FILMES Y VIDEOCINTAS', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE TELEVISIÓN', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE RADIO', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE PRODUCCIÓN DE RECITALES Y OTROS EVENTOS MUSICALES MASIVOS', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE PRODUCCIÓN TEATRAL Y OTROS N.C.P.', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES EMPRESARIALES DE ARTISTAS', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES ARTÍSTICAS; FUNCIONES DE ARTISTAS, ACTORES, MÚSICOS, CONFERENCISTAS, OTROS', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENCIAS DE VENTA DE BILLETES DE TEATRO, SALAS DE CONCIERTO Y DE TEATRO', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'INSTRUCTORES DE DANZA', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE DISCOTECAS, CABARET, SALAS DE BAILE Y SIMILARES', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE PARQUES DE ATRACCIONES Y CENTROS SIMILARES', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESPECTÁCULOS CIRCENSES, DE TÍTERES U OTROS SIMILARES', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE ENTRETENIMIENTO N.C.P.', 'SUB_RUB_COD' => 125 ]);
        App\Actividad::create([ 'ACT_DESC' => 'AGENCIAS DE NOTICIAS', 'SUB_RUB_COD' => 126 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS PERIODÍSTICOS PRESTADO POR PROFESIONALES', 'SUB_RUB_COD' => 126 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE BIBLIOTECAS Y ARCHIVOS', 'SUB_RUB_COD' => 127 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE MUSEOS Y PRESERVACIÓN DE LUGARES Y EDIFICIOS HISTÓRICOS', 'SUB_RUB_COD' => 127 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE JARDINES BOTÁNICOS Y ZOOLÓGICOS Y DE PARQUES NACIONALES', 'SUB_RUB_COD' => 127 ]);
        App\Actividad::create([ 'ACT_DESC' => 'EXPLOTACIÓN DE INSTALACIONES ESPECIALIZADAS PARA LAS PRACTICAS DEPORTIVAS', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE CLUBES DE DEPORTES Y ESTADIOS', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FUTBOL PROFESIONAL', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'FUTBOL AMATEUR', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'HIPÓDROMOS', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PROMOCIÓN Y ORGANIZACIÓN DE ESPECTÁCULOS DEPORTIVOS', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ESCUELAS PARA DEPORTES', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES RELACIONADAS AL DEPORTE N.C.P.', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SISTEMAS DE JUEGOS DE AZAR MASIVOS.', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE CASINO DE JUEGOS', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SALAS DE BILLAR, BOWLING, POOL Y JUEGOS ELECTRÓNICOS', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONTRATACIÓN DE ACTORES PARA CINE, TV, Y TEATRO', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTROS SERVICIOS DE DIVERSIÓN Y ESPARCIMIENTOS N.C.P.', 'SUB_RUB_COD' => 128 ]);
        App\Actividad::create([ 'ACT_DESC' => 'LAVADO Y LIMPIEZA DE PRENDAS DE TELA Y DE PIEL, INCLUSO LAS LIMPIEZAS EN SECO', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'PELUQUERÍAS Y SALONES DE BELLEZA', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS FUNERARIOS', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS EN CEMENTERIOS', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'SERVICIOS DE CARROZAS FÚNEBRES (TRANSPORTE DE CADÁVERES)', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE SERVICIOS FUNERARIOS Y OTRAS ACTIVIDADES CONEXAS', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ACTIVIDADES DE MANTENIMIENTO FÍSICO CORPORAL (BAÑOS, TURCOS, SAUNAS)', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'OTRAS ACTIVIDADES DE SERVICIOS PERSONALES N.C.P.', 'SUB_RUB_COD' => 129 ]);
        App\Actividad::create([ 'ACT_DESC' => 'HOGARES PRIVADOS INDIVIDUALES CON SERVICIO DOMÉSTICO', 'SUB_RUB_COD' => 130 ]);
        App\Actividad::create([ 'ACT_DESC' => 'CONSEJO DE ADMINISTRACIÓN DE EDIFICIOS Y CONDOMINIOS', 'SUB_RUB_COD' => 130 ]);
        App\Actividad::create([ 'ACT_DESC' => 'ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES', 'SUB_RUB_COD' => 131 ]);
    }
}
