<?php

use Illuminate\Database\Seeder;

class CiudadTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\Ciudad::create([ 'CIU_DESC' => 'Iquique', 'CIU_PV_COD' => 3]);
        App\Ciudad::create([ 'CIU_DESC' => 'Alto Hospicio', 'CIU_PV_COD' => 3]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pozo Almonte', 'CIU_PV_COD' => 4]);
        App\Ciudad::create([ 'CIU_DESC' => 'Camiña', 'CIU_PV_COD' => 4]);
        App\Ciudad::create([ 'CIU_DESC' => 'Colchane', 'CIU_PV_COD' => 4]);
        App\Ciudad::create([ 'CIU_DESC' => 'Huara', 'CIU_PV_COD' => 4]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pica', 'CIU_PV_COD' => 4]);
        App\Ciudad::create([ 'CIU_DESC' => 'Antofagasta', 'CIU_PV_COD' => 5]);
        App\Ciudad::create([ 'CIU_DESC' => 'Mejillones', 'CIU_PV_COD' => 5]);
        App\Ciudad::create([ 'CIU_DESC' => 'Sierra Gorda', 'CIU_PV_COD' => 5]);
        App\Ciudad::create([ 'CIU_DESC' => 'Taltal', 'CIU_PV_COD' => 5]);
        App\Ciudad::create([ 'CIU_DESC' => 'Calama', 'CIU_PV_COD' => 6]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ollagüe', 'CIU_PV_COD' => 6]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Pedro de Atacama', 'CIU_PV_COD' => 6]);
        App\Ciudad::create([ 'CIU_DESC' => 'Tocopilla', 'CIU_PV_COD' => 7]);
        App\Ciudad::create([ 'CIU_DESC' => 'María Elena', 'CIU_PV_COD' => 7]);
        App\Ciudad::create([ 'CIU_DESC' => 'Copiapó', 'CIU_PV_COD' => 8]);
        App\Ciudad::create([ 'CIU_DESC' => 'Caldera', 'CIU_PV_COD' => 8]);
        App\Ciudad::create([ 'CIU_DESC' => 'Tierra Amarilla', 'CIU_PV_COD' => 8]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chañaral', 'CIU_PV_COD' => 9]);
        App\Ciudad::create([ 'CIU_DESC' => 'Diego de Almagro', 'CIU_PV_COD' => 9]);
        App\Ciudad::create([ 'CIU_DESC' => 'Vallenar', 'CIU_PV_COD' => 10]);
        App\Ciudad::create([ 'CIU_DESC' => 'Alto del Carmen', 'CIU_PV_COD' => 10]);
        App\Ciudad::create([ 'CIU_DESC' => 'Freirina', 'CIU_PV_COD' => 10]);
        App\Ciudad::create([ 'CIU_DESC' => 'Huasco', 'CIU_PV_COD' => 10]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Serena', 'CIU_PV_COD' => 11]);
        App\Ciudad::create([ 'CIU_DESC' => 'Coquimbo', 'CIU_PV_COD' => 11]);
        App\Ciudad::create([ 'CIU_DESC' => 'Andacollo', 'CIU_PV_COD' => 11]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Higuera', 'CIU_PV_COD' => 11]);
        App\Ciudad::create([ 'CIU_DESC' => 'Paihuano', 'CIU_PV_COD' => 11]);
        App\Ciudad::create([ 'CIU_DESC' => 'Vicuña', 'CIU_PV_COD' => 11]);
        App\Ciudad::create([ 'CIU_DESC' => 'Illapel', 'CIU_PV_COD' => 12]);
        App\Ciudad::create([ 'CIU_DESC' => 'Canela', 'CIU_PV_COD' => 12]);
        App\Ciudad::create([ 'CIU_DESC' => 'Los Vilos', 'CIU_PV_COD' => 12]);
        App\Ciudad::create([ 'CIU_DESC' => 'Salamanca', 'CIU_PV_COD' => 12]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ovalle', 'CIU_PV_COD' => 13]);
        App\Ciudad::create([ 'CIU_DESC' => 'Combarbalá', 'CIU_PV_COD' => 13]);
        App\Ciudad::create([ 'CIU_DESC' => 'Monte Patria', 'CIU_PV_COD' => 13]);
        App\Ciudad::create([ 'CIU_DESC' => 'Punitaqui', 'CIU_PV_COD' => 13]);
        App\Ciudad::create([ 'CIU_DESC' => 'Río Hurtado', 'CIU_PV_COD' => 13]);
        App\Ciudad::create([ 'CIU_DESC' => 'Valparaíso', 'CIU_PV_COD' => 14]);
        App\Ciudad::create([ 'CIU_DESC' => 'Casablanca', 'CIU_PV_COD' => 14]);
        App\Ciudad::create([ 'CIU_DESC' => 'Concón', 'CIU_PV_COD' => 14]);
        App\Ciudad::create([ 'CIU_DESC' => 'Juan Fernández', 'CIU_PV_COD' => 14]);
        App\Ciudad::create([ 'CIU_DESC' => 'Puchuncaví', 'CIU_PV_COD' => 14]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quintero', 'CIU_PV_COD' => 14]);
        App\Ciudad::create([ 'CIU_DESC' => 'Viña del Mar', 'CIU_PV_COD' => 14]);
        App\Ciudad::create([ 'CIU_DESC' => 'Isla de Pascua', 'CIU_PV_COD' => 15]);
        App\Ciudad::create([ 'CIU_DESC' => 'Los Andes', 'CIU_PV_COD' => 16]);
        App\Ciudad::create([ 'CIU_DESC' => 'Calle Larga', 'CIU_PV_COD' => 16]);
        App\Ciudad::create([ 'CIU_DESC' => 'Rinconada', 'CIU_PV_COD' => 16]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Esteban', 'CIU_PV_COD' => 16]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Ligua', 'CIU_PV_COD' => 17]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cabildo', 'CIU_PV_COD' => 17]);
        App\Ciudad::create([ 'CIU_DESC' => 'Papudo', 'CIU_PV_COD' => 17]);
        App\Ciudad::create([ 'CIU_DESC' => 'Petorca', 'CIU_PV_COD' => 17]);
        App\Ciudad::create([ 'CIU_DESC' => 'Zapallar', 'CIU_PV_COD' => 17]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quillota', 'CIU_PV_COD' => 18]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Calera', 'CIU_PV_COD' => 18]);
        App\Ciudad::create([ 'CIU_DESC' => 'Hijuelas', 'CIU_PV_COD' => 18]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Cruz', 'CIU_PV_COD' => 18]);
        App\Ciudad::create([ 'CIU_DESC' => 'Nogales', 'CIU_PV_COD' => 18]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Antonio', 'CIU_PV_COD' => 19]);
        App\Ciudad::create([ 'CIU_DESC' => 'Algarrobo', 'CIU_PV_COD' => 19]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cartagena', 'CIU_PV_COD' => 19]);
        App\Ciudad::create([ 'CIU_DESC' => 'El Quisco', 'CIU_PV_COD' => 19]);
        App\Ciudad::create([ 'CIU_DESC' => 'El Tabo', 'CIU_PV_COD' => 19]);
        App\Ciudad::create([ 'CIU_DESC' => 'Santo Domingo', 'CIU_PV_COD' => 19]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Felipe', 'CIU_PV_COD' => 20]);
        App\Ciudad::create([ 'CIU_DESC' => 'Catemu', 'CIU_PV_COD' => 20]);
        App\Ciudad::create([ 'CIU_DESC' => 'Llay Llay', 'CIU_PV_COD' => 20]);
        App\Ciudad::create([ 'CIU_DESC' => 'Panquehue', 'CIU_PV_COD' => 20]);
        App\Ciudad::create([ 'CIU_DESC' => 'Putaendo', 'CIU_PV_COD' => 20]);
        App\Ciudad::create([ 'CIU_DESC' => 'Santa María', 'CIU_PV_COD' => 20]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quilpué', 'CIU_PV_COD' => 21]);
        App\Ciudad::create([ 'CIU_DESC' => 'Limache', 'CIU_PV_COD' => 21]);
        App\Ciudad::create([ 'CIU_DESC' => 'Olmué', 'CIU_PV_COD' => 21]);
        App\Ciudad::create([ 'CIU_DESC' => 'Villa Alemana', 'CIU_PV_COD' => 21]);
        App\Ciudad::create([ 'CIU_DESC' => 'Rancagua', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Codegua', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Coinco', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Coltauco', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Doñihue', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Graneros', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Las Cabras', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Machalí', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Malloa', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Mostazal', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Olivar', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Peumo', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pichidegua', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quinta de Tilcoco', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Rengo', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Requínoa', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Vicente', 'CIU_PV_COD' => 22]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pichilemu', 'CIU_PV_COD' => 23]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Estrella', 'CIU_PV_COD' => 23]);
        App\Ciudad::create([ 'CIU_DESC' => 'Litueche', 'CIU_PV_COD' => 23]);
        App\Ciudad::create([ 'CIU_DESC' => 'Marchihue', 'CIU_PV_COD' => 23]);
        App\Ciudad::create([ 'CIU_DESC' => 'Navidad', 'CIU_PV_COD' => 23]);
        App\Ciudad::create([ 'CIU_DESC' => 'Paredones', 'CIU_PV_COD' => 23]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Fernando', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chépica', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chimbarongo', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lolol', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Nancagua', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Palmilla', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Peralillo', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Placilla', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pumanque', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Santa Cruz', 'CIU_PV_COD' => 24]);
        App\Ciudad::create([ 'CIU_DESC' => 'Talca', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Constitución', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Curepto', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Empedrado', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Maule', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pelarco', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pencahue', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Río Claro', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Clemente', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Rafael', 'CIU_PV_COD' => 25]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cauquenes', 'CIU_PV_COD' => 26]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chanco', 'CIU_PV_COD' => 26]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pelluhue', 'CIU_PV_COD' => 26]);
        App\Ciudad::create([ 'CIU_DESC' => 'Curicó', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Hualañé', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Licantén', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Molina', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Rauco', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Romeral', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Sagrada Familia', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Teno', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Vichuquén', 'CIU_PV_COD' => 27]);
        App\Ciudad::create([ 'CIU_DESC' => 'Linares', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'Colbún', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'Longaví', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'Parral', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'Retiro', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Javier', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'Villa Alegre', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'Yerbas Buenas', 'CIU_PV_COD' => 28]);
        App\Ciudad::create([ 'CIU_DESC' => 'Concepción', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Coronel', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chiguayante', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Florida', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Hualqui', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lota', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Penco', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Pedro de la Paz', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Santa Juana', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Talcahuano', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Tomé', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Hualpén', 'CIU_PV_COD' => 29]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lebu', 'CIU_PV_COD' => 30]);
        App\Ciudad::create([ 'CIU_DESC' => 'Arauco', 'CIU_PV_COD' => 30]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cañete', 'CIU_PV_COD' => 30]);
        App\Ciudad::create([ 'CIU_DESC' => 'Contulmo', 'CIU_PV_COD' => 30]);
        App\Ciudad::create([ 'CIU_DESC' => 'Curanilahue', 'CIU_PV_COD' => 30]);
        App\Ciudad::create([ 'CIU_DESC' => 'Los Álamos', 'CIU_PV_COD' => 30]);
        App\Ciudad::create([ 'CIU_DESC' => 'Tirúa', 'CIU_PV_COD' => 30]);
        App\Ciudad::create([ 'CIU_DESC' => 'Los Ángeles', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Antuco', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cabrero', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Laja', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Mulchén', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Nacimiento', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Negrete', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quilaco', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quilleco', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Rosendo', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Santa Bárbara', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Tucapel', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Yumbel', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Alto Biobío', 'CIU_PV_COD' => 31]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chillán', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Bulnes', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cobquecura', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Coelemu', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Coihueco', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chillán Viejo', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'El Carmen', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ninhue', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ñiquén', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pemuco', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pinto', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Portezuelo', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quillón', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quirihue', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ránquil', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Carlos', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Fabián', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Ignacio', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Nicolás', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Treguaco', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Yungay', 'CIU_PV_COD' => 32]);
        App\Ciudad::create([ 'CIU_DESC' => 'Temuco', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Carahue', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cunco', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Curarrehue', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Freire', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Galvarino', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Gorbea', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lautaro', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Loncoche', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Melipeuco', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Nueva Imperial', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Padre las Casas', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Perquenco', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pitrufquén', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pucón', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Saavedra', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Teodoro Schmidt', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Toltén', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Vilcún', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Villarrica', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cholchol', 'CIU_PV_COD' => 33]);
        App\Ciudad::create([ 'CIU_DESC' => 'Angol', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Collipulli', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Curacautín', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ercilla', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lonquimay', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Los Sauces', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lumaco', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Purén', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Renaico', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Traiguén', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Victoria', 'CIU_PV_COD' => 34]);
        App\Ciudad::create([ 'CIU_DESC' => 'Puerto Montt', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Calbuco', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cochamó', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Fresia', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Frutillar', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Los Muermos', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Llanquihue', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Maullín', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Puerto Varas', 'CIU_PV_COD' => 37]);
        App\Ciudad::create([ 'CIU_DESC' => 'Castro', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ancud', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chonchi', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Curaco de Vélez', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Dalcahue', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Puqueldón', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Queilén', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quellón', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quemchi', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quinchao', 'CIU_PV_COD' => 38]);
        App\Ciudad::create([ 'CIU_DESC' => 'Osorno', 'CIU_PV_COD' => 39]);
        App\Ciudad::create([ 'CIU_DESC' => 'Puerto Octay', 'CIU_PV_COD' => 39]);
        App\Ciudad::create([ 'CIU_DESC' => 'Purranque', 'CIU_PV_COD' => 39]);
        App\Ciudad::create([ 'CIU_DESC' => 'Puyehue', 'CIU_PV_COD' => 39]);
        App\Ciudad::create([ 'CIU_DESC' => 'Río Negro', 'CIU_PV_COD' => 39]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Juan de la Costa', 'CIU_PV_COD' => 39]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Pablo', 'CIU_PV_COD' => 39]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chaitén', 'CIU_PV_COD' => 40]);
        App\Ciudad::create([ 'CIU_DESC' => 'Futaleufú', 'CIU_PV_COD' => 40]);
        App\Ciudad::create([ 'CIU_DESC' => 'Hualaihué', 'CIU_PV_COD' => 40]);
        App\Ciudad::create([ 'CIU_DESC' => 'Palena', 'CIU_PV_COD' => 40]);
        App\Ciudad::create([ 'CIU_DESC' => 'Coyhaique', 'CIU_PV_COD' => 41]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lago Verde', 'CIU_PV_COD' => 41]);
        App\Ciudad::create([ 'CIU_DESC' => 'Aysén', 'CIU_PV_COD' => 42]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cisnes', 'CIU_PV_COD' => 42]);
        App\Ciudad::create([ 'CIU_DESC' => 'Guaitecas', 'CIU_PV_COD' => 42]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cochrane', 'CIU_PV_COD' => 43]);
        App\Ciudad::create([ 'CIU_DESC' => 'O´Higgins', 'CIU_PV_COD' => 43]);
        App\Ciudad::create([ 'CIU_DESC' => 'Tortel', 'CIU_PV_COD' => 43]);
        App\Ciudad::create([ 'CIU_DESC' => 'Chile Chico', 'CIU_PV_COD' => 44]);
        App\Ciudad::create([ 'CIU_DESC' => 'Río Ibáñez', 'CIU_PV_COD' => 44]);
        App\Ciudad::create([ 'CIU_DESC' => 'Punta Arenas', 'CIU_PV_COD' => 45]);
        App\Ciudad::create([ 'CIU_DESC' => 'Laguna Blanca', 'CIU_PV_COD' => 45]);
        App\Ciudad::create([ 'CIU_DESC' => 'Río Verde', 'CIU_PV_COD' => 45]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Gregorio', 'CIU_PV_COD' => 45]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cabo de Hornos', 'CIU_PV_COD' => 46]);
        App\Ciudad::create([ 'CIU_DESC' => 'Antártica', 'CIU_PV_COD' => 46]);
        App\Ciudad::create([ 'CIU_DESC' => 'Porvenir', 'CIU_PV_COD' => 47]);
        App\Ciudad::create([ 'CIU_DESC' => 'Primavera', 'CIU_PV_COD' => 47]);
        App\Ciudad::create([ 'CIU_DESC' => 'Timaukel', 'CIU_PV_COD' => 47]);
        App\Ciudad::create([ 'CIU_DESC' => 'Natales', 'CIU_PV_COD' => 48]);
        App\Ciudad::create([ 'CIU_DESC' => 'Torres del Paine', 'CIU_PV_COD' => 48]);
        App\Ciudad::create([ 'CIU_DESC' => 'Santiago', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cerrillos', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Cerro Navia', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Conchalí', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'El Bosque', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Estación Central', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Huechuraba', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Independencia', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Cisterna', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Florida', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Granja', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Pintana', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Reina', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Las Condes', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lo Barnechea', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lo Espejo', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lo Prado', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Macul', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Maipú', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Ñuñoa', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pedro Aguirre Cerda', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Peñalolén', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Providencia', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pudahuel', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quilicura', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Quinta Normal', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Recoleta', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Renca', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Joaquín', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Miguel', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Ramón', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Vitacura', 'CIU_PV_COD' => 49]);
        App\Ciudad::create([ 'CIU_DESC' => 'Puente Alto', 'CIU_PV_COD' => 50]);
        App\Ciudad::create([ 'CIU_DESC' => 'Pirque', 'CIU_PV_COD' => 50]);
        App\Ciudad::create([ 'CIU_DESC' => 'San José de Maipo', 'CIU_PV_COD' => 50]);
        App\Ciudad::create([ 'CIU_DESC' => 'Colina', 'CIU_PV_COD' => 51]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lampa', 'CIU_PV_COD' => 51]);
        App\Ciudad::create([ 'CIU_DESC' => 'Tiltil', 'CIU_PV_COD' => 51]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Bernardo', 'CIU_PV_COD' => 52]);
        App\Ciudad::create([ 'CIU_DESC' => 'Buin', 'CIU_PV_COD' => 52]);
        App\Ciudad::create([ 'CIU_DESC' => 'Calera de Tango', 'CIU_PV_COD' => 52]);
        App\Ciudad::create([ 'CIU_DESC' => 'Paine', 'CIU_PV_COD' => 52]);
        App\Ciudad::create([ 'CIU_DESC' => 'Melipilla', 'CIU_PV_COD' => 53]);
        App\Ciudad::create([ 'CIU_DESC' => 'Alhué', 'CIU_PV_COD' => 53]);
        App\Ciudad::create([ 'CIU_DESC' => 'Curacaví', 'CIU_PV_COD' => 53]);
        App\Ciudad::create([ 'CIU_DESC' => 'María Pinto', 'CIU_PV_COD' => 53]);
        App\Ciudad::create([ 'CIU_DESC' => 'San Pedro', 'CIU_PV_COD' => 53]);
        App\Ciudad::create([ 'CIU_DESC' => 'Talagante', 'CIU_PV_COD' => 54]);
        App\Ciudad::create([ 'CIU_DESC' => 'El Monte', 'CIU_PV_COD' => 54]);
        App\Ciudad::create([ 'CIU_DESC' => 'Isla de Maipo', 'CIU_PV_COD' => 54]);
        App\Ciudad::create([ 'CIU_DESC' => 'Padre Hurtado', 'CIU_PV_COD' => 54]);
        App\Ciudad::create([ 'CIU_DESC' => 'Peñaflor', 'CIU_PV_COD' => 54]);
        App\Ciudad::create([ 'CIU_DESC' => 'Valdivia', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'Corral', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lanco', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'Los Lagos', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'Máfil', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'Mariquina', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'Paillaco', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'Panguipulli', 'CIU_PV_COD' => 35]);
        App\Ciudad::create([ 'CIU_DESC' => 'La Unión', 'CIU_PV_COD' => 36]);
        App\Ciudad::create([ 'CIU_DESC' => 'Futrono', 'CIU_PV_COD' => 36]);
        App\Ciudad::create([ 'CIU_DESC' => 'Lago Ranco', 'CIU_PV_COD' => 36]);
        App\Ciudad::create([ 'CIU_DESC' => 'Río Bueno', 'CIU_PV_COD' => 36]);
        App\Ciudad::create([ 'CIU_DESC' => 'Arica', 'CIU_PV_COD' => 1]);
        App\Ciudad::create([ 'CIU_DESC' => 'Camarones', 'CIU_PV_COD' => 1]);
        App\Ciudad::create([ 'CIU_DESC' => 'Putre', 'CIU_PV_COD' => 2]);
        App\Ciudad::create([ 'CIU_DESC' => 'General Lagos', 'CIU_PV_COD' => 2]);
    }
}
