<?php

use Illuminate\Database\Seeder;

class SubRubroTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        App\SubRubro::create([ 'RUB_COD' => 1, 'SUB_RUB_DESC' => 'CULTIVOS EN GENERAL; CULTIVO DE PRODUCTOS DE MERCADO; HORTICULTURA']);
        App\SubRubro::create([ 'RUB_COD' => 1, 'SUB_RUB_DESC' => 'CRÍA DE ANIMALES']);
        App\SubRubro::create([ 'RUB_COD' => 1, 'SUB_RUB_DESC' => 'CULTIVO PROD. AGRÍCOLAS EN COMBINACIÓN CON CRÍA DE ANIMALES']);
        App\SubRubro::create([ 'RUB_COD' => 1, 'SUB_RUB_DESC' => 'ACTIVIDADES DE SERVICIOS AGRÍCOLAS Y GANADEROS']);
        App\SubRubro::create([ 'RUB_COD' => 1, 'SUB_RUB_DESC' => 'CAZA ORDINARIA Y MEDIANTE TRAMPAS, REPOBLACIÓN, ACT. SERVICIO CONEXAS']);
        App\SubRubro::create([ 'RUB_COD' => 1, 'SUB_RUB_DESC' => 'SILVICULTURA, EXTRACCIÓN DE MADERA Y ACTIVIDADES DE SERVICIOS CONEXAS']);
        App\SubRubro::create([ 'RUB_COD' => 2, 'SUB_RUB_DESC' => 'EXPLT. DE CRIADEROS DE PECES Y PROD. DEL MAR; SERVICIOS RELACIONADOS']);
        App\SubRubro::create([ 'RUB_COD' => 2, 'SUB_RUB_DESC' => 'PESCA EXTRACTIVA: Y SERVICIOS RELACIONADOS']);
        App\SubRubro::create([ 'RUB_COD' => 3, 'SUB_RUB_DESC' => 'EXTRACCIÓN, AGLOMERACIÓN DE CARBÓN DE PIEDRA, LIGNITO Y TURBA']);
        App\SubRubro::create([ 'RUB_COD' => 3, 'SUB_RUB_DESC' => 'EXTRACCIÓN DE PETRÓLEO CRUDO Y GAS NATURAL; ACTIVIDADES RELACIONADAS']);
        App\SubRubro::create([ 'RUB_COD' => 3, 'SUB_RUB_DESC' => 'EXTRACCIÓN DE MINERALES METALÍFEROS']);
        App\SubRubro::create([ 'RUB_COD' => 3, 'SUB_RUB_DESC' => 'EXPLOTACIÓN DE MINAS Y CANTERAS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'PRODUCCIÓN, PROCESAMIENTO Y CONSERVACIÓN DE ALIMENTOS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ELABORACIÓN DE PRODUCTOS LÁCTEOS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ELAB. DE PROD. DE MOLINERÍA, ALMIDONES Y PROD. DERIVADOS DEL ALMIDÓN']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ELABORACIÓN DE OTROS PRODUCTOS ALIMENTICIOS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ELABORACIÓN DE BEBIDAS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ELABORACIÓN DE PRODUCTOS DEL TABACO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'HILANDERÍA, TEJEDURA Y ACABADO DE PRODUCTOS TEXTILES']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS TEXTILES']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE TEJIDOS Y ARTÍCULOS DE PUNTO Y GANCHILLO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE PRENDAS DE VESTIR; EXCEPTO PRENDAS DE PIEL']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'PROCESAMIENTO Y FABRICACIÓN DE ARTÍCULOS DE PIEL Y CUERO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE CALZADO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ASERRADO Y ACEPILLADURA DE MADERAS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FAB. DE PRODUCTOS DE MADERA Y CORCHO,  PAJA Y DE MATERIALES TRENZABLES']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE PAPEL Y PRODUCTOS DEL PAPEL']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ACTIVIDADES DE EDICIÓN']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ACTIVIDADES DE IMPRESIÓN Y DE SERVICIOS CONEXOS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE PRODUCTOS DE HORNOS COQUE Y DE REFINACIÓN DE PETRÓLEO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'ELABORACIÓN DE COMBUSTIBLE NUCLEAR']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE SUSTANCIAS QUÍMICAS BÁSICAS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE FIBRAS MANUFACTURADAS']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE PRODUCTOS DE CAUCHO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE PRODUCTOS DE PLÁSTICO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE VIDRIOS Y PRODUCTOS DE VIDRIO']);
        App\SubRubro::create([ 'RUB_COD' => 4, 'SUB_RUB_DESC' => 'FABRICACIÓN DE PRODUCTOS MINERALES NO METÁLICOS N.C.P.']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'INDUSTRIAS BÁSICAS DE HIERRO Y ACERO']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y METALES NO FERROSOS']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FUNDICIÓN DE METALES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. DE PROD. METÁLICOS PARA USO ESTRUCTURAL']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. DE OTROS PROD. ELABORADOS DE METAL; ACT. DE TRABAJO DE METALES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE MAQUINARIA DE USO GENERAL']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE MAQUINARIA DE USO ESPECIAL']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE APARATOS DE USO DOMÉSTICO N.C.P.']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE MAQUINARIA DE OFICINA, CONTABILIDAD E INFORMÁTICA']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. Y REPARACIÓN DE MOTORES, GENERADORES Y TRANSFORMADORES ELÉCTRICOS']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE APARATOS DE DISTRIBUCIÓN Y CONTROL; SUS REPARACIONES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE HILOS Y CABLES AISLADOS']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE ACUMULADORES DE PILAS Y BATERÍAS  PRIMARIAS']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN Y REPARACIÓN DE LÁMPARAS Y EQUIPO DE ILUMINACIÓN']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN Y REPARACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO N.C.P.']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE COMPONENTES ELECTRÓNICOS; SUS REPARACIONES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. Y REPARACIÓN DE TRANSMISORES DE RADIO, TELEVISIÓN, TELEFONÍA']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. DE RECEPTORES DE RADIO, TELEVISIÓN, APARATOS DE AUDIO/VÍDEO']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. DE APARATOS E INSTRUMENTOS MÉDICOS Y PARA REALIZAR MEDICIONES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. Y REPARACIÓN DE INSTRUMENTOS DE ÓPTICA Y EQUIPO FOTOGRÁFICO']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE RELOJES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE VEHÍCULOS AUTOMOTORES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'CONSTRUCCIÓN Y REPARACIÓN DE BUQUES Y OTRAS EMBARCACIONES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FAB. DE LOCOMOTORAS Y MATERIAL RODANTE PARA FERROCARRILES Y TRANVÍAS']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE AERONAVES Y NAVES ESPACIALES; SUS REPARACIONES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE OTROS TIPOS DE EQUIPO DE TRANSPORTE N.C.P.']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'FABRICACIÓN DE MUEBLES']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'INDUSTRIAS MANUFACTURERAS N.C.P.']);
        App\SubRubro::create([ 'RUB_COD' => 5, 'SUB_RUB_DESC' => 'RECICLAMIENTO DE DESPERDICIOS Y DESECHOS']);
        App\SubRubro::create([ 'RUB_COD' => 6, 'SUB_RUB_DESC' => 'GENERACIÓN, CAPTACIÓN Y DISTRIBUCIÓN DE ENERGÍA ELÉCTRICA']);
        App\SubRubro::create([ 'RUB_COD' => 6, 'SUB_RUB_DESC' => 'FABRICACIÓN DE GAS; DISTRIBUCIÓN DE COMBUSTIBLES GASEOSOS POR TUBERÍAS']);
        App\SubRubro::create([ 'RUB_COD' => 6, 'SUB_RUB_DESC' => 'SUMINISTRO DE VAPOR Y AGUA CALIENTE']);
        App\SubRubro::create([ 'RUB_COD' => 6, 'SUB_RUB_DESC' => 'CAPTACIÓN, DEPURACIÓN Y DISTRIBUCIÓN DE AGUA']);
        App\SubRubro::create([ 'RUB_COD' => 7, 'SUB_RUB_DESC' => 'CONSTRUCCIÓN']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA DE VEHÍCULOS AUTOMOTORES']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'MANTENIMIENTO Y REPARACIÓN DE VEHÍCULOS AUTOMOTORES']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA DE PARTES, PIEZAS Y ACCESORIOS DE VEHÍCULOS AUTOMOTORES']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA, MANTENIMIENTO Y REPARACIÓN DE MOTOCICLETAS Y SUS PARTES']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA AL POR MENOR DE COMBUSTIBLE  PARA AUTOMOTORES']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA AL POR MAYOR A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA AL POR MAYOR DE MATERIAS PRIMAS AGROPECUARIAS']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA AL POR MAYOR DE ENSERES DOMÉSTICOS']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA AL POR MAYOR DE PRODUCTOS INTERMEDIOS, DESECHOS NO AGROPECUARIOS']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA AL POR MAYOR DE MAQUINARÍA, EQUIPO Y MATERIALES CONEXOS']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'COMERCIO AL POR MENOR NO ESPECIALIZADO EN ALMACENES']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA POR MENOR DE ALIMENTOS, BEBIDAS, TABACOS EN ALMC. ESPECIALIZADOS']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'COMERCIO AL POR MENOR DE OTROS PROD. NUEVOS EN ALMC. ESPECIALIZADOS']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'VENTA AL POR MENOR EN ALMACENES DE ARTÍCULOS USADOS']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'COMERCIO AL POR MENOR NO REALIZADO EN ALMACENES']);
        App\SubRubro::create([ 'RUB_COD' => 8, 'SUB_RUB_DESC' => 'REPARACIÓN DE EFECTOS PERSONALES Y ENSERES DOMÉSTICOS']);
        App\SubRubro::create([ 'RUB_COD' => 9, 'SUB_RUB_DESC' => 'HOTELES; CAMPAMENTOS Y OTROS TIPOS DE HOSPEDAJE TEMPORAL']);
        App\SubRubro::create([ 'RUB_COD' => 9, 'SUB_RUB_DESC' => 'RESTAURANTES, BARES Y CANTINAS']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'TRANSPORTE POR FERROCARRILES']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'OTROS TIPOS DE TRANSPORTE POR VÍA TERRESTRE']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'TRANSPORTE POR TUBERÍAS']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'TRANSPORTE MARÍTIMO Y DE CABOTAJE']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'TRANSPORTE POR VÍAS DE NAVEGACIÓN INTERIORES']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'TRANSPORTE POR VÍA AÉREA']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'ACT. DE TRANSPORTE COMPLEMENTARIAS Y AUXILIARES; AGENCIAS DE VIAJE']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'ACTIVIDADES POSTALES Y DE CORREO']);
        App\SubRubro::create([ 'RUB_COD' => 10, 'SUB_RUB_DESC' => 'TELECOMUNICACIONES']);
        App\SubRubro::create([ 'RUB_COD' => 11, 'SUB_RUB_DESC' => 'INTERMEDIACIÓN MONETARIA']);
        App\SubRubro::create([ 'RUB_COD' => 11, 'SUB_RUB_DESC' => 'OTROS TIPOS DE INTERMEDIACIÓN FINANCIERA']);
        App\SubRubro::create([ 'RUB_COD' => 11, 'SUB_RUB_DESC' => 'ACT. AUX. DE LA INTERMEDIACIÓN FINANCIERA, EXCEPTO PLANES DE SEGUROS']);
        App\SubRubro::create([ 'RUB_COD' => 11, 'SUB_RUB_DESC' => 'ACT. AUXILIARES DE FINANCIACIÓN DE PLANES DE SEGUROS Y DE PENSIONES']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ACTIVIDADES INMOBILIARIAS REALIZADAS CON BIENES PROPIOS O ARRENDADOS']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ACT. INMOBILIARIAS REALIZADAS A CAMBIO DE RETRIBUCIÓN O POR CONTRATA']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ALQUILER EQUIPO DE TRANSPORTE']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ALQUILER DE OTROS TIPOS DE MAQUINARIA Y EQUIPO']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ALQUILER DE EFECTOS PERSONALES Y ENSERES DOMÉSTICOS N.C.P.']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'SERVICIOS INFORMÁTICOS']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'MANTENIMIENTO Y REPARACIÓN DE MAQUINARIA DE OFICINA']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ACTIVIDADES DE INVESTIGACIONES Y DESARROLLO EXPERIMENTAL']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ACTIVIDADES JURÍDICAS Y DE ASESORAMIENTO EMPRESARIAL EN GENERAL']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ACTIVIDADES DE ARQUITECTURA E INGENIERÍA Y OTRAS ACTIVIDADES TÉCNICAS']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'PUBLICIDAD']);
        App\SubRubro::create([ 'RUB_COD' => 12, 'SUB_RUB_DESC' => 'ACT. EMPRESARIALES Y DE PROFESIONALES PRESTADAS A EMPRESAS N.C.P.']);
        App\SubRubro::create([ 'RUB_COD' => 13, 'SUB_RUB_DESC' => 'GOBIERNO CENTRAL Y ADMINISTRACIÓN PÚBLICA']);
        App\SubRubro::create([ 'RUB_COD' => 13, 'SUB_RUB_DESC' => 'ACTIVIDADES DE PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA']);
        App\SubRubro::create([ 'RUB_COD' => 14, 'SUB_RUB_DESC' => 'ENSEÑANZA PREESCOLAR, PRIMARIA, SECUNDARIA Y SUPERIOR; PROFESORES']);
        App\SubRubro::create([ 'RUB_COD' => 15, 'SUB_RUB_DESC' => 'ACTIVIDADES RELACIONADAS CON LA SALUD HUMANA']);
        App\SubRubro::create([ 'RUB_COD' => 15, 'SUB_RUB_DESC' => 'ACTIVIDADES VETERINARIAS']);
        App\SubRubro::create([ 'RUB_COD' => 15, 'SUB_RUB_DESC' => 'ACTIVIDADES DE SERVICIOS SOCIALES']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'ELIMINACIÓN DE DESPERDICIOS Y AGUAS RESIDUALES, SANEAMIENTO']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'ACT. DE ORGANIZACIONES EMPRESARIALES, PROFESIONALES Y DE EMPLEADORES']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'ACTIVIDADES DE SINDICATOS Y DE OTRAS ORGANIZACIONES']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'ACT. DE CINEMATOGRAFÍA, RADIO Y TV Y OTRAS ACT. DE ENTRETENIMIENTO']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'ACTIVIDADES DE AGENCIAS DE NOTICIAS Y SERVICIOS PERIODISTICOS']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'ACTIVIDADES DE BIBLIOTECAS, ARCHIVOS Y MUSEOS Y OTRAS ACT. CULTURALES']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'ACTIVIDADES DEPORTIVAS Y OTRAS ACTIVIDADES DE ESPARCIMIENTO']);
        App\SubRubro::create([ 'RUB_COD' => 16, 'SUB_RUB_DESC' => 'OTRAS ACTIVIDADES DE SERVICIOS']);
        App\SubRubro::create([ 'RUB_COD' => 17, 'SUB_RUB_DESC' => 'CONSEJO DE ADMINISTRACION DE EDIFICIOS Y CONDOMINIOS']);
        App\SubRubro::create([ 'RUB_COD' => 18, 'SUB_RUB_DESC' => 'ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES']);
    }
}
